site_name: NIMPHEL
repo_url: https://github.com/servinagrero/nimphel
repo_name: nimphel
edit_uri: ""
theme:
    logo: img/logo.png
    name: material
    palette:
        primary: white
        accent: light blue
    font:
        text: Inter
        code: JetBrains Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.tabs
        - content.code.annotate

plugins:
  - search
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Introduction: index.md
    - Elements:
        - Components: elements/component.md
        - Subcircuits: elements/subcircuit.md
        - Circuits: elements/circuit.md
    - Manipulation: manipulation.md
    - Parsers: parsers.md
    - Exporters: exporters.md
